import scala.util.control.Exception._

/*start*/handling(classOf[Exception]).by((Exception) => 1L)/*end*/
//Exception.Catch[Long]